/* eslint-disable max-len */
export const ICONS = [
  'HOME', 'OFFICE', 'NEWSPAPER', 'PENCIL', 'EYEDROPPER', 'DROPLET', 'PAINT-FORMAT', 'CAMERA', 'HEADPHONES', 'MUSIC', 'PLAY',
  'VIDEO-CAMERA', 'DICE', 'SPADES', 'BULLHORN', 'CONNECTION', 'MIC', 'BOOK', 'LIBRARY', 'FILE-TEXT', 'PROFILE', 'FILE-EMPTY',
  'FILES-EMPTY', 'FILE-PICTURE', 'STACK', 'FOLDER', 'PRICE-TAG', 'PRICE-TAGS', 'QRCODE', 'CART', 'COIN-DOLLAR', 'CREDIT-CARD',
  'LIFEBUOY', 'PHONE', 'ADDRESS-BOOK', 'ENVELOP', 'PUSHPIN', 'LOCATION', 'COMPASS', 'MAP', 'CLOCK', 'ALARM', 'BELL', 'CALENDAR',
  'PRINTER', 'KEYBOARD', 'DISPLAY', 'MOBILE', 'TV', 'FLOPPY-DISK', 'UNDO', 'REDO', 'BUBBLE', 'BUBBLES', 'HOUR-GLASS', 'SPINNER',
  'BINOCULARS', 'SEARCH', 'KEY', 'LOCK', 'UNLOCKED', 'WRENCH', 'EQUALIZER', 'COG', 'AID-KIT', 'STATS-DOTS', 'TROPHY', 'GIFT',
  'GLASS', 'MUG', 'SPOON-KNIFE', 'LEAF', 'FIRE', 'LAB', 'BIN', 'BRIEFCASE', 'AIRPLANE', 'TRUCK', 'POWER', 'SWITCH', 'MENU', 'CLOUD',
  'EARTH', 'LINK', 'BOOKMARK', 'BOOKMARKS', 'STAR-EMPTY', 'STAR-FULL', 'HEART', 'HEART-BROKEN', 'MAN', 'WOMAN', 'MAN-WOMAN',
  'WARNING', 'PLUS', 'MINUS', 'INFO', 'CANCEL-CIRCLE', 'BLOCKED', 'CROSS', 'CHECKMARK', 'LOOP', 'TERMINAL', 'AMAZON', 'GOOGLE',
  'GOOGLE-PLUS', 'GOOGLE-DRIVE', 'FACEBOOK', 'INSTAGRAM', 'WHATSAPP', 'TWITTER', 'VK', 'FEED', 'STEAM', 'DROPBOX', 'ONEDRIVE',
  'GITHUB', 'WORDPRESS', 'TUX', 'APPLE', 'FINDER', 'ANDROID', 'WINDOWS', 'SOUNDCLOUD', 'SKYPE', 'REDDIT', 'LINKEDIN', 'CHROME',
  'FIREFOX', 'EDGE', 'SAFARI', 'OPERA', 'HTML-FIVE', 'GIT'
]

export const COLORS = {
  ICON_COLOR: '#131313'
//  ICON_COLOR: '#89cbf0'
}

export const SIZE = {
  ICON_SIZE: {
    WIDTH: '28',
    HEIGHT: '28'
  }
}
